DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQHQxLmNvbSIsImV4cCI6MTc1NDMzNDQzNiwidXNlcklkIjoxfQ.ABFC7kSdhFHZFaGD8z1GQimjx8LbxbvpCvddMDdRAjI