GET http://localhost:8080/events/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQHQxLmNvbSIsImV4cCI6MTc1NDMzODYxMCwidXNlcklkIjoxfQ.RzmMnIoxRY4k8abWYhCgGBTqpT27Bup8mG-gjTqZj-w