GET http://localhost:8080/events/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQyQHQyLmNvbSIsImV4cCI6MTc1NDQxNTY5MiwidXNlcklkIjo0fQ.RSAPNqzF5Xr189RiKLNKfUqxihUP7eMK39-PJi6-6MY