POST http://localhost:8080/register
Content-Type: application/json


{"email": "t1@t1.com",
"password": "t1!"} 

# {"email": "t2@t2.com",
# "password": "t2!"} 

# {"email": "t3@t3.com",
# "password": "t3!"} 