POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQyQHQyLmNvbSIsImV4cCI6MTc1NDMzMzI0MSwidXNlcklkIjowfQ.-LovJYqRV48vaSyBEn_q9ixQfy_s2w4H0nMd-Ejqmzs

{"name": "t2",
"description": "test descr", 
"datetime": "2025-02-02T20:50:30.000Z"} 