PUT http://localhost:8080/user/update-password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQHQxLmNvbSIsImV4cCI6MTc1NDQxMDY1MiwidXNlcklkIjoyfQ.F3agg3ycAtzZHS3aGCb2idABjXMhHWUTVVUMPgZHZgc



{"email": "t1@t1.com",
"password": "t1"} 
