PUT http://localhost:8080/events/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQHQxLmNvbSIsImV4cCI6MTc1NDQxMDY1MiwidXNlcklkIjoyfQ.F3agg3ycAtzZHS3aGCb2idABjXMhHWUTVVUMPgZHZgc



{"password": "t1"}
